apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: whisperx-transcription-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: whisperx-transcription-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
