apiVersion: v1
kind: Service
metadata:
  name: whisperx-transcription-service
spec:
  selector:
    app: whisperx-transcription-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
